/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.ABMAlumno;
import Entidades.Alumno;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author kalema
 */
public class AdminAlumnos extends javax.swing.JInternalFrame {

    public DefaultTableModel modelo = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int filas, int columnas) {
            return false;
        }
    };

    public DefaultTableModel edicion = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int f, int c) {
            return false;
        }

    };
    public static Alumno temp = new Alumno();
    public static ABMAlumno mod = new ABMAlumno();

    /**
     * Creates new form AdminAlumnos
     */
    public AdminAlumnos() {
        initComponents();
        armoTablaAlta();
        armoTablaEdicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAltaAlumnos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaAlta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtAltaNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtAltaApeliido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtAltaDNI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtAltaEstado = new javax.swing.JTextField();
        jtAltaFechaNac = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanelEdicionAlumnos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtEdicionBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaResultado = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jtEdicionNom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtEdicionApe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtEdicionFechaNac = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtEdicionDni = new javax.swing.JTextField();
        jbtActualizar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jtEdicionID = new javax.swing.JLabel();
        jtLabel = new javax.swing.JLabel();
        jtEdicionEstado = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTRACIÓN DE ALUMNOS");

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));

        jPanelAltaAlumnos.setBackground(new java.awt.Color(149, 175, 240));

        jTablaAlta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaAlta);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel2.setText("Nombre");
        jLabel2.setFocusable(false);

        jtAltaNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAltaNombreFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel3.setText("Fecha de Nacimineto");
        jLabel3.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel4.setText("Apellido");
        jLabel4.setFocusable(false);

        jtAltaApeliido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAltaApeliidoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel5.setText("DNI");
        jLabel5.setFocusable(false);

        jtAltaDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAltaDNIFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel6.setText("Estado");
        jLabel6.setFocusable(false);

        jtAltaEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAltaEstadoFocusLost(evt);
            }
        });

        jtAltaFechaNac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAltaFechaNacFocusLost(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Activo=1 - Desactivo=0");
        jLabel7.setFocusable(false);

        javax.swing.GroupLayout jPanelAltaAlumnosLayout = new javax.swing.GroupLayout(jPanelAltaAlumnos);
        jPanelAltaAlumnos.setLayout(jPanelAltaAlumnosLayout);
        jPanelAltaAlumnosLayout.setHorizontalGroup(
            jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltaAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanelAltaAlumnosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanelAltaAlumnosLayout.createSequentialGroup()
                        .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtAltaNombre)
                            .addComponent(jtAltaDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtAltaApeliido)
                            .addComponent(jtAltaEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtAltaFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanelAltaAlumnosLayout.setVerticalGroup(
            jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltaAlumnosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtAltaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtAltaApeliido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAltaFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtAltaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtAltaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanelAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alta de Alumnos", jPanelAltaAlumnos);

        jPanelEdicionAlumnos.setBackground(new java.awt.Color(193, 193, 193));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel8.setText("Búsqueda");
        jLabel8.setFocusable(false);

        jtEdicionBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtEdicionBusquedaKeyReleased(evt);
            }
        });

        jTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablaResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaResultadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaResultado);

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel9.setText("Nombre");
        jLabel9.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel10.setText("Apellido");
        jLabel10.setFocusable(false);

        jLabel11.setText("Identificador");
        jLabel11.setFocusable(false);

        jLabel12.setBackground(new java.awt.Color(233, 231, 231));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel13.setText("Fecha Nac");
        jLabel13.setFocusable(false);

        jLabel14.setText("DNI");

        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jtLabel.setText("Activo");
        jtLabel.setFocusable(false);

        jtEdicionEstado.setEditable(false);

        javax.swing.GroupLayout jPanelEdicionAlumnosLayout = new javax.swing.GroupLayout(jPanelEdicionAlumnos);
        jPanelEdicionAlumnos.setLayout(jPanelEdicionAlumnosLayout);
        jPanelEdicionAlumnosLayout.setHorizontalGroup(
            jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicionAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanelEdicionAlumnosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEdicionAlumnosLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtEdicionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEdicionAlumnosLayout.createSequentialGroup()
                        .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtActualizar)
                            .addGroup(jPanelEdicionAlumnosLayout.createSequentialGroup()
                                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEdicionAlumnosLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtEdicionID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanelEdicionAlumnosLayout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtEdicionDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtEdicionNom)
                                    .addComponent(jtEdicionEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jtEdicionApe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtEdicionFechaNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCancelar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(34, 34, 34))
        );
        jPanelEdicionAlumnosLayout.setVerticalGroup(
            jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdicionAlumnosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtEdicionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtEdicionNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtEdicionApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jtEdicionFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEdicionID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtEdicionDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLabel)
                    .addComponent(jtEdicionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelEdicionAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtActualizar)
                    .addComponent(jbtCancelar))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edición de Alumnos", jPanelEdicionAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean activo = false;
        temp.setNombre(jtAltaNombre.getText());
        temp.setApellido(jtAltaApeliido.getText());
        temp.setDni(Integer.parseInt(jtAltaDNI.getText()));
        temp.setFechaNacimiento(LocalDate.parse(jtAltaFechaNac.getText()));
        int valorActivo = Integer.parseInt(jtAltaEstado.getText());
        if (valorActivo == 1) {
            activo = true;
        }

        temp.setEstado(activo);
        mod.insertoDatos(temp);
        armoFilas();
        jtAltaNombre.setText("");
        jtAltaApeliido.setText("");
        jtAltaFechaNac.setText("");
        jtAltaEstado.setText("");
        jtAltaDNI.setText("");
        jtAltaNombre.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Cancelo la carga de el Alumno. Vacio los campos
        jtAltaNombre.setText("");
        jtAltaApeliido.setText("");
        jtAltaDNI.setText("");
        jtAltaFechaNac.setText("");
        jtAltaEstado.setText("");
        jtAltaNombre.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtAltaNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAltaNombreFocusLost
        if (jtAltaNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo NOMBRE no puede estar vacío");
            jtAltaNombre.requestFocus();
            jtAltaNombre.selectAll();
        }
    }//GEN-LAST:event_jtAltaNombreFocusLost

    private void jtAltaApeliidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAltaApeliidoFocusLost
        if (jtAltaApeliido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo APELLIDO no puede estar vacío");
            jtAltaApeliido.requestFocus();
            jtAltaApeliido.selectAll();
        }
    }//GEN-LAST:event_jtAltaApeliidoFocusLost

    private void jtAltaFechaNacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAltaFechaNacFocusLost
        if (jtAltaFechaNac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo FECHA DE NACIMIENTO no puede estar vacío");
            jtAltaFechaNac.requestFocus();
            jtAltaFechaNac.selectAll();
        }
    }//GEN-LAST:event_jtAltaFechaNacFocusLost

    private void jtAltaDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAltaDNIFocusLost
        if (jtAltaFechaNac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo DNI no puede estar vacío");
            jtAltaDNI.requestFocus();
            jtAltaDNI.selectAll();
        }
    }//GEN-LAST:event_jtAltaDNIFocusLost

    private void jtAltaEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAltaEstadoFocusLost
        if (jtAltaEstado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo ESTADO no puede estar vacío");
            jtAltaEstado.requestFocus();
            jtAltaEstado.selectAll();
        }
    }//GEN-LAST:event_jtAltaEstadoFocusLost

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        jtEdicionID.setText("");
        jtEdicionApe.setText("");
        jtEdicionNom.setText("");
        jtEdicionFechaNac.setText("");
        jtEdicionDni.setText("");
        jtEdicionEstado.setText("");
        jtEdicionBusqueda.requestFocus();
        jtEdicionBusqueda.selectAll();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jtEdicionBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEdicionBusquedaKeyReleased
        ResultSet seleccion = mod.selecAlumno();
        borrarFilas();
        try {
            while (seleccion.next()) {
                if (jtEdicionBusqueda.getText().isEmpty()) {
                    borrarFilas();
                } else if (seleccion.getString("nombre").startsWith(jtEdicionBusqueda.getText())
                        || seleccion.getString("apellido").startsWith(jtEdicionBusqueda.getText())) {
                    edicion.addRow(new Object[]{seleccion.getInt(1), seleccion.getInt(2), seleccion.getString("apellido"),
                        seleccion.getString("nombre"), seleccion.getString("fechaNacimiento"),
                        seleccion.getString("estado")});
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al consultar la base de datos");
        }
    }//GEN-LAST:event_jtEdicionBusquedaKeyReleased

    private void jTablaResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaResultadoMouseClicked
       int valor=jTablaResultado.getSelectedRow();
       String id=String.valueOf(jTablaResultado.getValueAt(valor, 0));
       String nom=String.valueOf(jTablaResultado.getValueAt(valor, 1));
       String ape=String.valueOf(jTablaResultado.getValueAt(valor, 2));
       String dni=String.valueOf(jTablaResultado.getValueAt(valor, 3));
       String fecha=String.valueOf(jTablaResultado.getValueAt(valor, 4));
       String activo=String.valueOf(jTablaResultado.getValueAt(valor, 5));
       jtEdicionID.setText(id);
       jtEdicionNom.setText(nom);
       jtEdicionApe.setText(ape);
       jtEdicionFechaNac.setText(fecha);
       jtEdicionDni.setText(dni);
       jtEdicionEstado.setText(activo);
    }//GEN-LAST:event_jTablaResultadoMouseClicked

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        temp.setIdAlumno(Integer.parseInt(jtEdicionID.getText()));
        temp.setApellido(jtEdicionApe.getText());
        temp.setNombre(jtEdicionNom.getText());
        temp.setDni(Integer.parseInt(jtEdicionDni.getText()));
        temp.setFechaNacimiento(LocalDate.parse(jtEdicionFechaNac.getText()));
        int esActivo=Integer.parseInt(jtEdicionEstado.getText());
        if(esActivo==1){
            temp.setEstado(true);
        }else{
            temp.setEstado(false);
        }
        mod.modificoAlumno(temp);
    }//GEN-LAST:event_jbtActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAltaAlumnos;
    private javax.swing.JPanel jPanelEdicionAlumnos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablaAlta;
    private javax.swing.JTable jTablaResultado;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JTextField jtAltaApeliido;
    private javax.swing.JTextField jtAltaDNI;
    private javax.swing.JTextField jtAltaEstado;
    private javax.swing.JTextField jtAltaFechaNac;
    private javax.swing.JTextField jtAltaNombre;
    private javax.swing.JTextField jtEdicionApe;
    private javax.swing.JTextField jtEdicionBusqueda;
    private javax.swing.JTextField jtEdicionDni;
    private javax.swing.JTextField jtEdicionEstado;
    private javax.swing.JTextField jtEdicionFechaNac;
    private javax.swing.JLabel jtEdicionID;
    private javax.swing.JTextField jtEdicionNom;
    private javax.swing.JLabel jtLabel;
    // End of variables declaration//GEN-END:variables

    private void armoTablaAlta() {
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Activo");
        jTablaAlta.setModel(modelo);
    }

    private void armoFilas() {
        modelo.addRow(new Object[]{jtAltaNombre.getText(), jtAltaApeliido.getText(), jtAltaDNI.getText(), jtAltaFechaNac.getText(),
            jtAltaEstado.getText()});
    }

    private void armoTablaEdicion() {
        edicion.addColumn("Identificador");
        edicion.addColumn("Nombre");
        edicion.addColumn("Apellido");
        edicion.addColumn("DNI");
        edicion.addColumn("Fecha de Nacimiento");
        edicion.addColumn("Estado");
        jTablaResultado.setModel(edicion);
    }

    private void borrarFilas() {
        int filas = edicion.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            edicion.removeRow(i);

        }
    }
}
