/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.SelectAcceso;
import Vistas.Acceso;

/**
 *
 * @author kalema
 */
public class PanelSistema extends javax.swing.JFrame {
    
    public static boolean nivel_1=false,nivel_2=false,nivel_3=false;
    public Acceso datos=new Acceso();
    //public static int valor=Acceso.acceso.getElGrupo();
    /**
     * Creates new form PanelSistema
     */
    public PanelSistema() {
        initComponents();
        controlAcceso();
        jMtnuLogeo.setText(SelectAcceso.acceso.getNombre());
        jMtnuLogeo2.setText(SelectAcceso.acceso.getApellido());
        permisosMenu();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmItemAdminAlumnos = new javax.swing.JMenuItem();
        jmItemAdminMaterias = new javax.swing.JMenuItem();
        jmItemUsuarios = new javax.swing.JMenuItem();
        jmItemBajaAlmuno = new javax.swing.JMenuItem();
        jmItemGestorAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMtnuLogeo = new javax.swing.JMenu();
        jMtnuLogeo2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jmAdministracion.setText("Administación");
        jmAdministracion.setMaximumSize(new java.awt.Dimension(117, 32767));

        jmItemAdminAlumnos.setText("Administración de Alumnos");
        jmItemAdminAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemAdminAlumnosActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmItemAdminAlumnos);

        jmItemAdminMaterias.setText("Administración de Materias");
        jmItemAdminMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemAdminMateriasActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmItemAdminMaterias);

        jmItemUsuarios.setText("Alta/baja de Usuarios");
        jmAdministracion.add(jmItemUsuarios);

        jmItemBajaAlmuno.setText("Baja alumnos");
        jmAdministracion.add(jmItemBajaAlmuno);

        jmItemGestorAlumno.setText("Gestión de Alumnos");
        jmItemGestorAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemGestorAlumnoActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmItemGestorAlumno);

        jMenuBar1.add(jmAdministracion);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setEnabled(false);
        jMenu3.setFocusable(false);
        jMenu3.setMaximumSize(new java.awt.Dimension(406, 32767));
        jMenu3.setRequestFocusEnabled(false);
        jMenu3.setRolloverEnabled(false);
        jMenu3.setVerifyInputWhenFocusTarget(false);
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Usuario");
        jMenu1.setEnabled(false);
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMaximumSize(new java.awt.Dimension(66, 32767));
        jMenu1.setRequestFocusEnabled(false);
        jMenu1.setRolloverEnabled(false);
        jMenu1.setVerifyInputWhenFocusTarget(false);
        jMenuBar1.add(jMenu1);

        jMtnuLogeo.setEnabled(false);
        jMtnuLogeo.setFocusable(false);
        jMtnuLogeo.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMtnuLogeo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMtnuLogeo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMtnuLogeo.setMaximumSize(new java.awt.Dimension(76, 32767));
        jMtnuLogeo.setRequestFocusEnabled(false);
        jMtnuLogeo.setRolloverEnabled(false);
        jMtnuLogeo.setVerifyInputWhenFocusTarget(false);
        jMenuBar1.add(jMtnuLogeo);

        jMtnuLogeo2.setEnabled(false);
        jMtnuLogeo2.setFocusable(false);
        jMtnuLogeo2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jMtnuLogeo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMtnuLogeo2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMtnuLogeo2.setMaximumSize(new java.awt.Dimension(76, 32767));
        jMtnuLogeo2.setRequestFocusEnabled(false);
        jMtnuLogeo2.setRolloverEnabled(false);
        jMtnuLogeo2.setVerifyInputWhenFocusTarget(false);
        jMenuBar1.add(jMtnuLogeo2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemAdminAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemAdminAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AdminAlumnos adminAlum=new AdminAlumnos();
        adminAlum.setVisible(true);
        escritorio.add(adminAlum);
        
    }//GEN-LAST:event_jmItemAdminAlumnosActionPerformed

    private void jmItemAdminMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemAdminMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AdminMaterias adminMat=new AdminMaterias();
        adminMat.setVisible(true);
        escritorio.add(adminMat);
    }//GEN-LAST:event_jmItemAdminMateriasActionPerformed

    private void jmItemGestorAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemGestorAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestorAlumnos gestor=new GestorAlumnos();
        gestor.setVisible(true);
        escritorio.add(gestor);
    }//GEN-LAST:event_jmItemGestorAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMtnuLogeo;
    private javax.swing.JMenu jMtnuLogeo2;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenuItem jmItemAdminAlumnos;
    private javax.swing.JMenuItem jmItemAdminMaterias;
    private javax.swing.JMenuItem jmItemBajaAlmuno;
    private javax.swing.JMenuItem jmItemGestorAlumno;
    private javax.swing.JMenuItem jmItemUsuarios;
    // End of variables declaration//GEN-END:variables

    private void controlAcceso(){
        int valor=SelectAcceso.acceso.getElGrupo();
        switch (valor) {
            case 1:
                nivel_1=true;
                break;
            case 2:
                nivel_2=true;
                break;
            default:
                nivel_3=true;
                break;
        }
        jmItemAdminAlumnos.setEnabled(false);
        jmItemAdminMaterias.setEnabled(false);
        jmItemBajaAlmuno.setEnabled(false);
        jmItemUsuarios.setEnabled(false);
        jmItemGestorAlumno.setEnabled(false);
    }
    
    public void permisosMenu(){
        if(nivel_3==true){
            jmItemAdminAlumnos.setEnabled(true);
        }else if(nivel_2==true){
            jmItemAdminAlumnos.setEnabled(true);
            jmItemAdminMaterias.setEnabled(true);
        }else {
            jmItemAdminAlumnos.setEnabled(true);
            jmItemAdminMaterias.setEnabled(true);
            jmItemBajaAlmuno.setEnabled(true);
            jmItemUsuarios.setEnabled(true);
            jmItemGestorAlumno.setEnabled(true);
        }
    }

}
